# Generated by Django 4.0.3 on 2022-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0002_remove_beverage_stock_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='beverage',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
