# Generated by Django 4.0.3 on 2022-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0004_beverage_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text='Price, for which the beverage has been bought', max_digits=4),
        ),
    ]
