# Generated by Django 4.0.3 on 2022-03-28 15:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0006_beverage_price_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
