# Generated by Django 4.0.3 on 2022-03-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beverage", "0002_remove_beverage_stock_prices"),
        ("stock_price", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="beverage",
            field=models.ForeignKey(
                default=1.0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stock_prices",
                to="beverage.beverage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
