# Generated by Django 4.0.3 on 2022-03-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0002_stockprice_beverage_alter_stockprice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-pk']},
        ),
    ]
