# Generated by Django 4.0.3 on 2022-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0003_alter_stockprice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
