# Generated by Django 4.0.3 on 2022-03-27 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0004_alter_stockprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 16, 42, 18, 52786, tzinfo=utc), help_text='Time at which this price has been issued'),
        ),
    ]
