# Generated by Django 4.0.3 on 2022-03-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beverage', '0009_remove_beverage_price_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock', to='beverage.beverage')),
            ],
            options={
                'ordering': ['beverage'],
            },
        ),
    ]
